### ISSUE TITLE
Context dropdown needs to be shown when cursor moves between lines

### ISSUE THREAD

**Issue by cmbirk** [JohnMcLear/ep_context#4]
Right now only shows on click-in.  Is there a way to show it when the cursor is moved via the arrow keys?  Maybe the `active` selector?

**Comment by JohnMcLear** [comment]
Will sort this np.

**Comment by JohnMcLear** [comment]
Resolved :)  Pull and test..  Can't use active because as the document moves around it needs to be reflected on the viewers screen so have to use an idle work timer..  This is probably not optimized though and could be more optimized should we look to see if editor content has changed..  But even then wrapping etc.
